apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  type: NodePort # LoadBalancer | ClusterIP
  ports:
  - name: http
    port: 8040
    targetPort: 8040
    protocol: TCP